package com.caribresort.actions;

public interface RequestAction {
	//Bartender Actions
	String SERVE="SERVE";
	String OPEN="OPEN";
	
	//Customer Actions
	String MAKEORDER = "MAKEORDER";
	String ADDITEMTOORDER="ADDITEMTOORDER";
	
	//Manager Actions
	String GENERATEREPORT = "GENERATEREPORT";
    String ADDDRINK = "ADDDRINKR";
	String REMOVEDRINK = "REMOVEDRINK";
	String UPDATEDRINK = "UPDATEDRINK";
	
	//Manager CRUD 
	
	    //INSERTS 
	String ADDARMBAND="ADDARMBAND";
	String ADDCUSTOMERORDER="ADDCUSTOMERORDER";
	String ADDCUSTOMERORDERITEM="ADDCUSTOMERORDERITEM";
	String ADDDRINKTYPE="ADDDRINKTYPE";
	String ADDEMPLOYEE="ADDEMPLOYEE";
	String ADDGUEST="ADDGUEST";
	String ADDROLE="ADDROLE";
	
         //UPDATE
	String UPDARMBAND="UPDARMBAND";
	String UPDCUSTOMERORDER="UPDCUSTOMERORDER";
	String UPDCUSTOMERORDERITEM="UPDCUSTOMERORDERITEM";
	String UPDDRINKTYPE="UPDDRINKTYPE";
	String UPDEMPLOYEE="UPDEMPLOYEE";
	String UPDGUEST="UPDGUEST";
	String UPDROLE="UPDROLE";
	
        //DELETE
	String DELARMBAND="DELARMBAND";
	String DELCUSTOMERORDER="DELCUSTOMERORDER";
	String DELCUSTOMERORDERITEM="DELCUSTOMERORDERITEM";
	String DELDRINKTYPE="DELDRINKTYPE";
	String DELEMPLOYEE="DELEMPLOYEE";
	String DELGUEST="DELGUEST";
	String DELROLE="DELROLE";
	
	    //GET
	String GETARMBAND="GETARMBAND";
	String GETCUSTOMERORDER="GETCUSTOMERORDER";
	String GETCUSTOMERORDERITEM="GETCUSTOMERORDERITEM";
	String GETDRINKTYPE="GETDRINKTYPE";
	String GETEMPLOYEE="GETEMPLOYEE";
	String GETGUEST="GETGUEST";
	String GETROLE="GETROLE";
	
	   //SELECT ALL
	String ALLARMBAND="ALLARMBAND";
	String ALLCUSTOMERORDER="ALLCUSTOMERORDER";
	String ALLCUSTOMERORDERITEM="ALLCUSTOMERORDERITEM";
	String ALLDRINKTYPE="ALLDRINKTYPE";
	String ALLEMPLOYEE="ALLEMPLOYEE";
	String ALLGUEST="ALLGUEST";
	String ALLROLE="ALLROLE";
	
	//All User Actions
	String VIEWDRINKS = "VIEWDRINKS";
	String VIEWDRINKTYPES = "VIEWDRINKTYPES";
}
