package com.caribresort.entity;
// Generated Feb 25, 2014 2:21:24 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements CaribResortEntity {


     /**
	 * 
	 */
	private static final long serialVersionUID = 4913922394946552886L;
	private Integer roleId;
     private String roleName;
     private Set<Employee> employees = new HashSet<Employee>();

    public Role() {
    }

    public Role(String roleName, Set<Employee> employees) {
       this.roleName = roleName;
       this.employees = employees;
    }
   
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }

	@Override
	public Object PopulateFromArray(Object[] data) {
		// TODO Auto-generated method stub
		return null;
	}




}


