package com.caribresort.entity;
// Generated Feb 25, 2014 2:21:24 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customerorder generated by hbm2java
 */
public class Customerorder  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -280839847584993770L;
	private Integer customerOrderId;
     private Guest guest;
     private Employee employee;
     private Date orderDate;
     private Set<Customerorderitem> customerorderitems = new HashSet<Customerorderitem>(0);

    public Customerorder() {
    }

    public Customerorder(Guest guest, Employee employee, Date orderDate, Set<Customerorderitem> customerorderitems) {
       this.guest = guest;
       this.employee = employee;
       this.orderDate = orderDate;
       this.customerorderitems = customerorderitems;
    }
   
    public Integer getCustomerOrderId() {
        return this.customerOrderId;
    }
    
    public void setCustomerOrderId(Integer customerOrderId) {
        this.customerOrderId = customerOrderId;
    }
    public Guest getGuest() {
        return this.guest;
    }
    
    public void setGuest(Guest guest) {
        this.guest = guest;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public Set<Customerorderitem> getCustomerorderitems() {
        return this.customerorderitems;
    }
    
    public void setCustomerorderitems(Set<Customerorderitem> customerorderitems) {
        this.customerorderitems = customerorderitems;
    }




}


